# Site
title: Teerapong Singthong
description: Because i'm just an ordinary person who focused on 'Development'
url: https://iamgoangle.github.io
#url: http://127.0.0.1:4000
logo: golf-logo.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/golf-home.png                           # this image will be shown on homepage's left block
  post-list: images/12043050_982005851847216_7927084816037540014_n.jpg             # this image will be shown on post list page
  default-post: images/post-wall.png   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:categories/:year/:month/:day/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email:              st.teerapong@gmail.com
#google.plus:        username
twitter:            iamgoangle
facebook:           goangle
github:             iamgoangle
stackoverflow:      6495718/teerapong-singthong
linkedin:           goangle
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
steam:              goangle
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
